### ISSUE TITLE
something wrong when i used gpu

### ISSUE THREAD

**Issue by yrd241** [yuichiro-s/chainer-bot#2]
Thank you for your codes!

But i find when I run my program add --gpu=0 , a error will be reported.

The error is:
`python train.py input_zh vocab_zh chat_model --hidden=[4096,4096] --lstm --gpu=0`
`Copying vocabulary to chat_model/vocab
Loading vocabulary from vocab_zh
Vocabulary size: 191706
Loading training data from input_zh
Creating batches...
Training started.
Traceback (most recent call last):
  File "train.py", line 95, in <module>
    main(parser.parse_args())
  File "train.py", line 66, in main
    util.train(s2s, batches, optimizer, args.model, max_epoch=None, gpu=args.gpu, save_every=args.save_every, get_status=_get_status)
  File "/home/yrd/chainer-bot-master/scripts/bot/util.py", line 97, in train
    optimizer.setup(model.model)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 69, in setup
    self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 84, in prepare
    self.init_state(param, state)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizers/adam.py", line 25, in init_state
    state['v'] = xp.zeros_like(param.data)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/basic.py", line 167, in zeros_like
    return zeros(a.shape, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/basic.py", line 144, in zeros
    a = empty(shape, dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype=dtype)
  File "cupy/core/core.pyx", line 107, in cupy.core.core.ndarray.__init__ (cupy/core/core.cpp:5103)
  File "cupy/cuda/memory.pyx", line 250, in cupy.cuda.memory.alloc (cupy/cuda/memory.cpp:5101)
  File "cupy/cuda/memory.pyx", line 378, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:7447)
  File "cupy/cuda/memory.pyx", line 394, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:7367)
  File "cupy/cuda/memory.pyx", line 312, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:6550)
  File "cupy/cuda/memory.pyx", line 327, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:6374)
  File "cupy/cuda/memory.pyx", line 230, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5040)
  File "cupy/cuda/memory.pyx", line 231, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:4955)
  File "cupy/cuda/memory.pyx", line 29, in cupy.cuda.memory.Memory.__init__ (cupy/cuda/memory.cpp:1373)
  File "cupy/cuda/runtime.pyx", line 164, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:2700)
  File "cupy/cuda/runtime.pyx", line 106, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1815)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory`

Firstly,i considered maybe the batch_size is very large,so i modified it smaller,but the error still existed.

Do you know how can i solve this problem? thanks .

**Comment by yuichiro-s** [comment]
Hi. I think the vocabulary size and the hidden layer sizes are quite large. Have you considered reducing them?

**Comment by yrd241** [comment]
Yes, I reduced them and the program worked  based on GPU.  : )

**Comment by yuichiro-s** [comment]
Great :)
